var searchData=
[
  ['cloud_5fblob',['cloud_blob',['../classazure_1_1storage_1_1cloud__blob.html',1,'azure::storage']]],
  ['cloud_5fblob_5fclient',['cloud_blob_client',['../classazure_1_1storage_1_1cloud__blob__client.html',1,'azure::storage']]],
  ['cloud_5fblob_5fcontainer',['cloud_blob_container',['../classazure_1_1storage_1_1cloud__blob__container.html',1,'azure::storage']]],
  ['cloud_5fblob_5fcontainer_5fproperties',['cloud_blob_container_properties',['../classazure_1_1storage_1_1cloud__blob__container__properties.html',1,'azure::storage']]],
  ['cloud_5fblob_5fdirectory',['cloud_blob_directory',['../classazure_1_1storage_1_1cloud__blob__directory.html',1,'azure::storage']]],
  ['cloud_5fblob_5fproperties',['cloud_blob_properties',['../classazure_1_1storage_1_1cloud__blob__properties.html',1,'azure::storage']]],
  ['cloud_5fblob_5fshared_5faccess_5fheaders',['cloud_blob_shared_access_headers',['../classazure_1_1storage_1_1cloud__blob__shared__access__headers.html',1,'azure::storage']]],
  ['cloud_5fblock_5fblob',['cloud_block_blob',['../classazure_1_1storage_1_1cloud__block__blob.html',1,'azure::storage']]],
  ['cloud_5fclient',['cloud_client',['../classazure_1_1storage_1_1cloud__client.html',1,'azure::storage']]],
  ['cloud_5fpage_5fblob',['cloud_page_blob',['../classazure_1_1storage_1_1cloud__page__blob.html',1,'azure::storage']]],
  ['cloud_5fpermissions',['cloud_permissions',['../classazure_1_1storage_1_1cloud__permissions.html',1,'azure::storage']]],
  ['cloud_5fpermissions_3c_20blob_5fshared_5faccess_5fpolicy_20_3e',['cloud_permissions&lt; blob_shared_access_policy &gt;',['../classazure_1_1storage_1_1cloud__permissions.html',1,'azure::storage']]],
  ['cloud_5fpermissions_3c_20queue_5fshared_5faccess_5fpolicy_20_3e',['cloud_permissions&lt; queue_shared_access_policy &gt;',['../classazure_1_1storage_1_1cloud__permissions.html',1,'azure::storage']]],
  ['cloud_5fpermissions_3c_20table_5fshared_5faccess_5fpolicy_20_3e',['cloud_permissions&lt; table_shared_access_policy &gt;',['../classazure_1_1storage_1_1cloud__permissions.html',1,'azure::storage']]],
  ['cloud_5fqueue',['cloud_queue',['../classazure_1_1storage_1_1cloud__queue.html',1,'azure::storage']]],
  ['cloud_5fqueue_5fclient',['cloud_queue_client',['../classazure_1_1storage_1_1cloud__queue__client.html',1,'azure::storage']]],
  ['cloud_5fqueue_5fmessage',['cloud_queue_message',['../classazure_1_1storage_1_1cloud__queue__message.html',1,'azure::storage']]],
  ['cloud_5fstorage_5faccount',['cloud_storage_account',['../classazure_1_1storage_1_1cloud__storage__account.html',1,'azure::storage']]],
  ['cloud_5ftable',['cloud_table',['../classazure_1_1storage_1_1cloud__table.html',1,'azure::storage']]],
  ['cloud_5ftable_5fclient',['cloud_table_client',['../classazure_1_1storage_1_1cloud__table__client.html',1,'azure::storage']]],
  ['container_5flisting_5fdetails',['container_listing_details',['../structazure_1_1storage_1_1container__listing__details.html',1,'azure::storage']]],
  ['continuation_5ftoken',['continuation_token',['../classazure_1_1storage_1_1continuation__token.html',1,'azure::storage']]],
  ['copy_5fstate',['copy_state',['../classazure_1_1storage_1_1copy__state.html',1,'azure::storage']]],
  ['cors_5frule',['cors_rule',['../classazure_1_1storage_1_1service__properties_1_1cors__rule.html',1,'azure::storage::service_properties']]]
];
